{
  "name" : "Continuous Integration",
  "on" : {
    "push" : {
      "paths" : [
        "**"
      ]
    },
    "pull_request" : {
      "paths" : [
        "**"
      ]
    }
  },
  "env" : {
    "CMAKE_GENERATOR" : "Ninja",
    "HOMEBREW_NO_ANALYTICS": "1",
    "HOMEBREW_NO_AUTO_UPDATE": "1",
    "HOMEBREW_NO_INSTALL_UPGRADE": "1",
    "HOMEBREW_NO_INSTALL_CLEANUP": "1",
    "DEBIAN_FRONTEND": "noninteractive",
    "TZ": "Japan"
  },
  "jobs" : {
    "build-ubuntu" : {
      "runs-on": "ubuntu-latest",
      "timeout-minutes": 20,
      "container": {
        "image": "ghcr.io/homebrew/ubuntu22.04:latest",
        "options": "--user 0"
      },
      "steps" : [
        {
          "name" : "Install required dependencies",
          "run" : "apt-get -y update && apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' install build-essential git python3"
        },
        {
          "name" : "Checkout repository and submodules recursively",
          "uses" : "actions/checkout@v4",
          "with" : {
            "submodules" : "recursive"
          }
        },
        {
          "name" : "Set up Homebrew environment for Github Actions",
          "run" : "printf '%s\\n' '/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin' >> $GITHUB_PATH"
        },
        {
          "name" : "Set up default build tools",
          "run" : "sudo -H -E -u linuxbrew bash -c 'cd /home/linuxbrew && /home/linuxbrew/.linuxbrew/bin/brew install make cmake ninja googletest'"
        },
        {
          "name" : "Configure project",
          "run" : "cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_AUTOMATED_TESTS=ON"
        },
        {
          "name" : "Build project",
          "run" : "cmake --build build"
        },
        {
          "name" : "Test project",
          "run" : "cmake --build build --target test"
        }
      ]
    },
    "build-ubuntu-win32" : {
      "runs-on": "ubuntu-latest",
      "timeout-minutes": 20,
      "container": {
        "image": "ghcr.io/homebrew/ubuntu22.04:latest",
        "options": "--user 0"
      },
      "strategy" : {
        "fail-fast" : false,
        "matrix" : {
          "platform" : [
            {
              "triplet" : "i686-w64-mingw32",
              "cmake-system-compiler" : "i686",
              "compiler" : "gcc"
            },
            {
              "triplet" : "x86_64-w64-mingw32",
              "cmake-system-compiler" : "amd64",
              "compiler" : "gcc"
            }
          ]
        }
      },
      "steps" : [
        {
          "name" : "Install required dependencies",
          "run" : "apt-get -y update && apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' install build-essential git python3"
        },
        {
          "name" : "Checkout repository and submodules recursively",
          "uses" : "actions/checkout@v4",
          "with" : {
            "submodules" : "recursive"
          }
        },
        {
          "name" : "Set up Homebrew environment for Github Actions",
          "run" : "printf '%s\\n' '/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin' >> $GITHUB_PATH"
        },
        {
          "name" : "Set up default build tools",
          "run" : "sudo -H -E -u linuxbrew bash -c 'cd /home/linuxbrew && /home/linuxbrew/.linuxbrew/bin/brew install make nasm cmake ninja'"
        },
        {
          "name" : "Set up mingw-w64 for GCC",
          "if" : "matrix.platform.compiler == 'gcc'",
          "run" : "sudo -H -E -u linuxbrew bash -c 'cd /home/linuxbrew && /home/linuxbrew/.linuxbrew/bin/brew install mingw-w64'"
        },
        {
          "name" : "Configure project",
          "run" : "cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.platform.cmake-system-compiler }} -DCMAKE_FIND_ROOT_PATH=/dev/null -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY -DCMAKE_C_COMPILER=${{ matrix.platform.triplet }}-gcc -DCMAKE_CXX_COMPILER=${{ matrix.platform.triplet }}-g++ -DCMAKE_RC_COMPILER=${{ matrix.platform.triplet }}-windres"
        },
        {
          "name" : "Build project",
          "run" : "cmake --build build"
        }
      ]
    },
    "build-ubuntu-pico" : {
      "runs-on": "ubuntu-latest",
      "timeout-minutes": 20,
      "container": {
        "image": "ubuntu:22.04",
        "options": "--user 0"
      },
      "steps" : [
        {
          "name" : "Install required dependencies",
          "run" : "apt-get -y update && apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' install build-essential cmake ninja-build git python3"
        },
        {
          "name" : "Checkout repository and submodules recursively",
          "uses" : "actions/checkout@v4",
          "with" : {
            "submodules" : "recursive"
          }
        },
        {
          "name" : "Install required dependencies for Raspberry Pi Pico target",
          "run" : "apt-get -y update && apt-get -y -o Dpkg::Options::='--force-confdef' -o Dpkg::Options::='--force-confold' install gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib"
        },
        {
          "name" : "Set environment variable PICO_PATH for Raspberry Pi Pico",
          "run" : "printf '%s\\n' \"PICO_PATH=$(pwd)/pico\" >> $GITHUB_ENV"
        },
        {
          "name" : "Set environment variable PICO_SDK_PATH for Raspberry Pi Pico",
          "run" : "printf '%s\\n' \"PICO_SDK_PATH=${{ env.PICO_PATH }}/pico-sdk/\" >> $GITHUB_ENV"
        },
        {
          "name" : "Make directory for Pico path",
          "run" : "mkdir -p $PICO_PATH"
        },
        {
          "name" : "Clone Raspberry Pi Pico SDK",
          "run" : "git clone -b 1.5.1 --single-branch --recursive https://github.com/raspberrypi/pico-sdk.git $PICO_SDK_PATH"
        },
        {
          "name" : "Configure project",
          "run" : "cmake -S . -B build -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DTARGET_RASPI_PICO=ON"
        },
        {
          "name" : "Build project",
          "run" : "cmake --build build"
        },
        {
          "uses" : "actions/upload-artifact@v4",
          "with" : {
            "name" : "ValvaeLibre-pico",
            "path" : "build/*.uf2"
          }
        }
      ]
    }
  }
}
